# Generated by Django 3.2 on 2021-04-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default=None, verbose_name='Комментарии'),
        ),
    ]
